name: ci

on:
  push:
    branches: [main, ci-inotify-tools]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: erlef/setup-beam@v1
        with:
          otp-version: "23"
          elixir-version: "1.12.2"

      - uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}

      - run: mix deps.get
      - run: mix format --check-formatted

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.3-alpine
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2

      - uses: erlef/setup-beam@v1
        with:
          otp-version: "23"
          elixir-version: "1.12.2"

      - uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}

      - run: mix deps.get

      - run: sudo apt-get install -y inotify-tools # https://hexdocs.pm/phoenix/installation.html#inotify-tools-for-linux-users
      - run: mix test
